CREATE DATABASE PROJETO_INTERDISCIPLICAR_II;
USE PROJETO_INTERDISCIPLICAR_II;

CREATE TABLE TB_USUARIO (
    ID INT AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    NIVEL CHAR(3) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE TB_POSTAGEM (
	ID INT AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    IMAGEM VARCHAR(255) NOT NULL,
    CONTEUDO TEXT NOT NULL,
    ATIVO INT NOT NULL DEFAULT 0,
    
    ID_USUARIO_FK INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
    REFERENCES TB_USUARIO(ID)
);

CREATE TABLE TB_CURTIDA (
	CURTIDA CHAR(1) NOT NULL,
	
	ID_USUARIO_FK INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
    REFERENCES TB_USUARIO(ID),
    
    ID_POSTAGEM_FK INT NOT NULL,
    CONSTRAINT ID_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM_FK)
    REFERENCES TB_POSTAGEM(ID)
);

CREATE TABLE TB_COMENTARIO (
	COMENTARIO VARCHAR(255),

	ID_USUARIO_FK INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
    REFERENCES TB_USUARIO(ID),
    
    ID_POSTAGEM_FK INT NOT NULL,
    CONSTRAINT ID_POSTAGEM_FK FOREIGN KEY (ID_POSTAGEM_FK)
    REFERENCES TB_POSTAGEM(ID)
);